# Generated by Django 5.2.13 on 2026-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrecord',
            name='client_name',
            field=models.CharField(default='Cliente no indicado', max_length=150),
        ),
        migrations.AddField(
            model_name='contractrecord',
            name='contract_type',
            field=models.CharField(choices=[('rental', 'Alquiler'), ('nda', 'NDA / Confidencialidad'), ('general', 'General')], default='rental', max_length=20),
        ),
    ]
