# Generated by Django 5.2.13 on 2026-04-29 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contractrecord_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='engine',
            field=models.CharField(default='rules', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='key_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='llm_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractrecord',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contractrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractrecord',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
